# Generated by Django 5.0.6 on 2024-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0001_initial'),
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Category',
        ),
    ]
