# Generated by Django 5.0.6 on 2024-06-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0002_rename_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='taskModel',
        ),
    ]
