# Generated by Django 5.0.6 on 2024-06-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0003_remove_category_taskmodel'),
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='taskCategory.category'),
        ),
    ]
